apiVersion: v1
kind: Service
metadata:
  name: coupon-api
  namespace: coupon
  labels:
    app: coupon-api
spec:
  type: NodePort
  selector:
    app: coupon-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
