apiVersion: v1
kind: Service
metadata:
  name: coupon-mysql
  namespace: coupon
  labels:
    app: coupon-mysql
spec:
  ports:
    - port: 3306
      name: coupon-mysql
  clusterIP: None
  selector:
    app: coupon-mysql
