apiVersion: v1
kind: Service
metadata:
  name: coupon-redis
  namespace: coupon
  labels:
    app: coupon-redis
spec:
  ports:
    - port: 6379
      name: coupon-redis
  clusterIP: None
  selector:
    app: coupon-redis
